language: python
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  - env: TARGET=mypy
  - env: TARGET=pep8
  allow_failures:
  - env: TARGET=pep8
  - env: TARGET=mypy
sudo: required
services:
- docker
install:
- true
script:
- docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: svw26
  password:
    secure: j9a7KxzSwoCqqwYQ57NJ+bZmhRiNLAbF5U3Uup2wY3azUofPeDJwdw7mLOjwZ28C9FZDbpQ8BYggG4b0Wn2eme2z9XoGfyXRN7uHyNnhhgjwj+Ha0p8POfm5dUhNgRAra1tpbUjIh8LmiQueG9/r2BxnB7NzrFo2NfwVk4Ez0vJV3qyPmcJQ7nfkpaPUozzWqb9VW/cvqLLYLnCKcWvLwPPZMCaRgQiODHwx7IFZFgW2xIPouz7DJ81ty9IId1nfrpcHUsVDzIA06+JNuNug9/WFcnH6JNHjRu1zZgYLpeEg+AHjb+ybT3AAUnbYNyvVDHa1ripNv3mmkNZ9JlQVv4L4QiMC6XnlLq2REJyYg96trnaoMLRw+s8y80QNOvcQXecYA2EkuTb0H+TkO6fgXpG7dHHDMfCrjZC5T8raUHOU8k03fE++pAtpqzFlizy29wW5gL1Z6x3Gx9eBawGufMGEP0CtWxULAjMmlZ/95ROI34vjaG3POdd9furax8YVuBSrxhxkqww4RBoT7lMhyDeM+cGsXgoLmufnAiX7zv33M88Bg5kuWVvKsR9FDqUnL/a+wi8kWfDMgRM0NXtzvSsEoTo+zlIUk2/zhbDjqZh9+8ea9gE+LydiEztRFlBIsmYH/V0XLmG/U5lztF+BiX+h3uTkbMv34kUw5kWpAt8=
  true:
    tags: true
    repo: svw26/MosaicSteward
