# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - "*"   # Triggers on push to any branch, including new ones
    tags:
      - "*"    # Triggers on push to any tag
  pull_request:
  schedule:
    - cron: '30 2 * * 1'  # Every Monday at 2:30 AM UTC

env:
  UV_VERSION: 0.9.9

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
      - name: Test uv
        run: uv --version
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python dependencies with uv
        run: uv sync
      - name: Install dependencies
        run: |
          uv pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run flake8 mosaicqueen --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          uv run flake8 mosaicqueen --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test command
        run: uv run mosaic-queen --help
